name: beta build
on:
  push:
    branches: [ main ]
        
jobs:
  Deploy-to-beta:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Beta Build
        run: |
           echo long
           echo ${{ github.sha }}
           
           
           echo short
           echo ${GITHUB_SHA::6}
